### PR TITLE
Adds functionality that lets this work for players

### PR DESCRIPTION
**Pull request by Grygon**
Per #5 this is something that'd be really neat for players to have in LANCER. Adds a setting that lets the GM control whether to do that.

### CODE REVIEW

**Comment by Grygon** [comment]
Bump, any chance this'll get pulled in? Keep having to point Lancer people at my fork

**Comment by Grygon** [comment]
@tsrgit @trdischat poke

**Comment by trdischat** [comment]
If you want players to see unexplored areas, why not just turn off FOW?

**Comment by Grygon** [comment]
[A gif from the Lancer discord showing this in action](https://cdn.discordapp.com/attachments/760966283545673730/822809447931052052/LOS.gif)

Basically, in Lancer there's the expectation that you know where terrain is, but may not know where enemies are. With my patched lessfog + another custom module (sensor-sight) you can replicate this pretty well, and automatically show LoS.

If you don't want to merge it in that's fine, I just keep having to tell people how to custom-install my fork and was hoping to get it in officially.

**Comment by trdischat** [comment]
Thanks for the explanation, Grygon.  Been buried with real life lately and haven't been able to dig into this. Also, I'm concerned with what Atropos has in store in version 0.8.x that may make this model obsolete.  When I get a chance, I will look at your mod and get back to you.

**Comment by Grygon** [comment]
Makes sense, and no real rush, I'll just leave it open--just wanted to make sure it was being looked at! Can definitely keep pushing people to my fork until we're ready for 0.8

**Comment by trdischat** [comment]
@Grygon, it took me several hours to figure out how to merge a pull request on Github, but I think I pulled it off.  Let me know if I screwed it up.

**Pull request merged**
